name: Development Progress
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 소스코드를 VM 에 담는다
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      # ci 서버를 위한 clean install 을 수행한다
      - run: npm ci
      - run: npm run build
      - run: npm run build:types
      - run: npm publish
      - name: 'context'

        env:
          COMMIT_ID: ${{ github.sha }}
        run: echo "Commit id => $COMMIT_ID"

      - name: 'api obj'
        env:
          FIREBASE_API_OBJ: ${{ secrets.FIREBASE_API_OBJ }}
        run: echo "firebase api obj => $FIREBASE_API_OBJ"

      # Runs a set of commands using the runners shell
      - name: Run ls -al
        run: ls -al
